load_fname: null
num_crawl_steps: 2
generation_batch_size: 5
max_topic_string_length: 200
max_crawl_topics: 1000
max_generated_tokens: 3000
max_refusal_check_generated_tokens: 512
max_extracted_topics_per_generation: 10
num_refusal_checks_per_topic: 4
is_refusal_threshold: 0.25
seed_warmup_steps: 1
do_filter_refusals: false
max_concurrent_summarizations: 10
prompt_languages:
  - chinese
verbose: true
output_dir: null
run_tag: null
