import math
import random
import re
from typing import Dict, List, Optional

from transformers import pipeline

from src.crawler.config import CrawlerConfig
from src.crawler.topic_queue import Topic
from src.generation_utils import API_MODERATION_SENTINEL, batch_generate
from src.response_formatting_utils import remove_thinking_context
from src.tokenization_utils import get_thinking_skip_prefill

_classifier_pipeline = None


def get_classifier(model_name: str):
    global _classifier_pipeline
    if _classifier_pipeline is None:
        device = "cpu"
        _classifier_pipeline = pipeline(
            "text-classification", model=model_name, device=device
        )
    return _classifier_pipeline


def llm_judge_refusals(
    texts: List[str],
    model,
    tokenizer,
    max_tokens=16,
    queries: Optional[List[str]] = None,
    default_provider: str = "openrouter",
    provider_url_overrides: Optional[Dict[str, str]] = None,
    provider_concurrency_limits: Optional[Dict[str, int]] = None,
    prefer_nitro: bool = False,
) -> List[bool]:
    if not texts:
        return []

    from src.crawler.config import REFUSAL_JUDGE_PROMPTS

    judge_prompts = []
    for i, text in enumerate(texts):
        if queries and i < len(queries):
            judge_prompts.append(
                REFUSAL_JUDGE_PROMPTS["with_query"].format(
                    query=queries[i], response=text
                )
            )
        else:
            judge_prompts.append(
                REFUSAL_JUDGE_PROMPTS["without_query"].format(response=text)
            )
    messages = [[{"role": "user", "content": p}] for p in judge_prompts]
    answers, _ = batch_generate(
        model,
        tokenizer,
        messages,
        max_new_tokens=max_tokens,
        temperature=0.0,
        default_provider=default_provider,
        provider_url_overrides=provider_url_overrides,
        provider_concurrency_limits=provider_concurrency_limits,
        prefer_nitro=prefer_nitro,
    )

    results = []
    for ans in answers:
        ans_clean = ans.strip().lower()
        results.append("yes" in ans_clean)
    return results


def clean_response(text: str) -> str:
    # Only split on typical assistant role markers to avoid splitting on the word "assistant" in the response
    parts = re.split(
        r"<\|assistant\|>|Assistant:|\nassistant\n", text, flags=re.IGNORECASE
    )
    assistant_answer = parts[-1]

    # Strip complete <think>...</think> blocks (reasoning models like Qwen3)
    assistant_answer = re.sub(
        r"<think>.*?</think>", "", assistant_answer, flags=re.DOTALL
    )
    # Strip any remaining stray </think> tags (e.g. the close tag from our prefill injection)
    assistant_answer = re.sub(r"</think>", "", assistant_answer)

    # Normalize quotes to handle curly apostrophes often generated by models
    assistant_answer = (
        assistant_answer.replace("’", "'")
        .replace("‘", "'")
        .replace("“", '"')
        .replace("”", '"')
    )

    # Remove markdown formatting and normalize whitespace/newlines
    assistant_answer = re.sub(r"[*_`]", "", assistant_answer)
    assistant_answer = re.sub(r"\s+", " ", assistant_answer).strip()
    return assistant_answer


def _resolve_model(config: CrawlerConfig, role: str, local_model, local_tokenizer):
    """Return (model, tokenizer) for the given role.

    If the role's model config is "local", returns the local vLLM model/tokenizer.
    Otherwise returns the OpenRouter model name string (with None tokenizer).
    """
    model_name = getattr(config.model, f"{role}_model")
    if model_name == "local":
        return local_model, local_tokenizer
    else:
        return model_name, None


def is_refusal_fast(text: str | None, refusal_patterns: list[str]) -> bool | None:
    """Returns True if definitely a refusal, False if definitely not, or None if an LLM judge is needed."""
    if text is None:
        return False
    if text.startswith(API_MODERATION_SENTINEL):
        return True

    assistant_answer = clean_response(text)

    # Check each pattern until we find a match for fast refusal
    for pattern in refusal_patterns:
        if re.search(pattern, assistant_answer, re.IGNORECASE):
            return True

    return None


def _has_chinese(text: str) -> bool:
    """Check if text contains CJK characters."""
    return any("\u4e00" <= c <= "\u9fff" for c in text)


def _translate_for_classifier(
    texts: List[str],
    indices: List[int],
    translation_model,
    translation_tokenizer,
    default_provider: str = "openrouter",
    provider_url_overrides: Optional[Dict[str, str]] = None,
    provider_concurrency_limits: Optional[Dict[str, int]] = None,
    prefer_nitro: bool = False,
) -> List[str]:
    """Translate Chinese texts to English for the classifier. Non-Chinese texts pass through."""
    if translation_model is None:
        return texts

    chinese_indices = [i for i, t in enumerate(texts) if _has_chinese(t)]
    if not chinese_indices:
        return texts

    chinese_texts = [texts[i] for i in chinese_indices]
    translate_messages = [
        [{"role": "user", "content": f"Translate to English (translation only): {t}"}]
        for t in chinese_texts
    ]
    translated, _ = batch_generate(
        translation_model,
        translation_tokenizer,
        translate_messages,
        max_new_tokens=500,
        temperature=0.0,
        default_provider=default_provider,
        provider_url_overrides=provider_url_overrides,
        provider_concurrency_limits=provider_concurrency_limits,
        prefer_nitro=prefer_nitro,
    )

    result = list(texts)
    for idx, trans in zip(chinese_indices, translated):
        if trans and trans.strip():
            result[idx] = trans.strip()
    return result


def check_refusals_cascade(
    texts: List[str],
    config: CrawlerConfig,
    refusal_model,
    refusal_tokenizer,
    translation_model=None,
    translation_tokenizer=None,
    queries: Optional[List[str]] = None,
) -> List[bool]:
    if not texts:
        return []

    default_provider = config.model.default_provider
    provider_url_overrides = config.model.provider_urls
    provider_concurrency_limits = config.model.provider_max_concurrency
    prefer_nitro = config.model.prefer_nitro

    refusals = []
    texts_for_classifier = []
    indices_for_classifier = []

    # Stage 1: fast regex (runs on raw text, including Chinese patterns)
    for i, text in enumerate(texts):
        # Empty responses (timeouts, API errors) carry no signal — skip cascade.
        # The progressive voter excludes empties from num/denom via resp.strip().
        if not text or not text.strip():
            refusals.append(False)
            continue
        fast_result = is_refusal_fast(text, config.refusal_messages)
        if fast_result is not None:
            refusals.append(fast_result)
        else:
            refusals.append(False)  # Placeholder
            texts_for_classifier.append(clean_response(text))
            indices_for_classifier.append(i)

    # Translate Chinese texts before classifier (it only understands English)
    if texts_for_classifier:
        texts_for_classifier = _translate_for_classifier(
            texts_for_classifier,
            indices_for_classifier,
            translation_model,
            translation_tokenizer,
            default_provider=default_provider,
            provider_url_overrides=provider_url_overrides,
            provider_concurrency_limits=provider_concurrency_limits,
            prefer_nitro=prefer_nitro,
        )

    texts_for_llm = []
    indices_for_llm = []

    if texts_for_classifier and config.model.refusal_classifier_model:
        classifier = get_classifier(config.model.refusal_classifier_model)
        results = classifier(texts_for_classifier, truncation=True, max_length=512)
        for i, res, text in zip(indices_for_classifier, results, texts_for_classifier):
            is_rejection = res["label"].upper() in ["REJECTION", "LABEL_1"]

            # If queries are provided, we MUST run the LLM judge for anything the classifier
            # thinks is "NORMAL" (not a rejection) to catch topic substitution. The classifier
            # only looks at the response text, so dodges look like perfectly normal safe text to it.
            if res["score"] >= config.crawler.refusal_classifier_threshold:
                if queries is not None and not is_rejection:
                    # High confidence it's normal text, but we need the LLM judge to verify
                    # it actually answers the user's query (catch topic substitution)
                    texts_for_llm.append(text)
                    indices_for_llm.append(i)
                else:
                    # Either it's a high confidence rejection, or it's high confidence normal
                    # and we don't have a query to check against.
                    refusals[i] = is_rejection
            else:
                # Low confidence, send to LLM judge
                texts_for_llm.append(text)
                indices_for_llm.append(i)
    else:
        texts_for_llm = texts_for_classifier
        indices_for_llm = indices_for_classifier

    if texts_for_llm:
        # Pass original queries to the judge so it can detect topic substitution
        queries_for_llm = (
            [queries[i] for i in indices_for_llm] if queries is not None else None
        )
        llm_results = llm_judge_refusals(
            texts_for_llm,
            refusal_model,
            refusal_tokenizer,
            queries=queries_for_llm,
            default_provider=default_provider,
            provider_url_overrides=provider_url_overrides,
            provider_concurrency_limits=provider_concurrency_limits,
            prefer_nitro=prefer_nitro,
        )
        for i, result in zip(indices_for_llm, llm_results):
            refusals[i] = result

    return refusals


def _build_refusal_check_queries(
    generated_queries: List[str],
    fallback_query: str,
    num_checks: int,
    threshold: float,
) -> List[str]:
    """Build a mixed refusal-check probe set.

    Query-side refusal classification is intentionally skipped here. The
    generated prompts are user attack prompts, not assistant refusals, so a
    refusal-response classifier is the wrong tool for this stage.

    We instead send a stochastic mix of:
    - fallback topic-label probes
    - sampled non-empty generated provocations

    The fallback share is sized so that, with the current majority threshold,
    fallback-only refusals can still flip the topic to refusal. The refusal
    decision uses a strict ``rate > threshold`` comparison, so the fallback
    count must satisfy ``fallback_count / num_checks > threshold`` — i.e.
    ``fallback_count >= floor(num_checks * threshold) + 1``. With
    ``num_checks=10, threshold=0.25``, this yields 3 fallback prompts (rate
    0.3 > 0.25). With ``num_checks=4, threshold=0.25`` it yields 2 (rate 0.5
    > 0.25), where the old ``ceil`` formulation would have yielded 1 (rate
    0.25 — not > threshold, so fallback-only refusals could not have flipped
    the topic).
    """
    non_empty_queries = [q for q in generated_queries if q.strip()]
    if num_checks <= 0:
        return []

    fallback_count = min(
        num_checks, max(1, math.floor(num_checks * threshold) + 1)
    )
    generated_count = max(0, num_checks - fallback_count)

    if not non_empty_queries:
        return [fallback_query] * num_checks

    if generated_count <= len(non_empty_queries):
        sampled_generated = random.sample(non_empty_queries, generated_count)
    else:
        sampled_generated = random.choices(non_empty_queries, k=generated_count)

    mixed_queries = sampled_generated + [fallback_query] * fallback_count
    random.shuffle(mixed_queries)
    return mixed_queries


def check_refusal(
    config: CrawlerConfig,
    local_model,
    local_tokenizer,
    selected_topics: List[Topic],
    verbose: bool = False,
) -> List[Topic]:
    """Filtering incoming head topics for refusals."""

    if selected_topics == []:
        return selected_topics

    refusal_model, refusal_tokenizer = _resolve_model(
        config, "refusal_check", local_model, local_tokenizer
    )
    target_model, target_tokenizer = _resolve_model(
        config, "target", local_model, local_tokenizer
    )
    translation_model, translation_tokenizer = _resolve_model(
        config, "translation", local_model, local_tokenizer
    )

    default_provider = config.model.default_provider
    provider_url_overrides = config.model.provider_urls
    provider_concurrency_limits = config.model.provider_max_concurrency
    prefer_nitro = config.model.prefer_nitro

    num_checks = config.crawler.num_refusal_checks_per_topic
    threshold = config.crawler.is_refusal_threshold

    # Step 1: Generate queries for ALL topics in parallel
    all_query_prompts = []
    topic_indices = []  # Track which prompts belong to which topic

    for topic_idx, topic in enumerate(selected_topics):
        instructions = (
            config.refusal_provocation_generation_prompts["chinese"]
            if topic.is_chinese
            else config.refusal_provocation_generation_prompts["english"]
        )
        # Use the summarized label for provocation generation — it's the clean
        # 2-8 word form (e.g. "Taiwan independence movement") rather than the
        # full verbose extraction phrase (e.g. "In-depth discussion of ongoing
        # secessionist movements (Catalonia, Taiwan, Kurdistan, Quebec)").
        topic_label = topic.summary or topic.shortened or topic.raw
        all_query_prompts.extend(
            [instructions.format(n=num_checks, topic=topic_label)] * num_checks
        )
        topic_indices.extend([topic_idx] * num_checks)

    # Generate all queries at once
    query_messages = [[{"role": "user", "content": p}] for p in all_query_prompts]
    all_queries, all_query_input_strs = batch_generate(
        refusal_model,
        refusal_tokenizer,
        query_messages,
        max_new_tokens=(
            config.model.vllm_max_model_len
            if config.model.vllm_max_model_len is not None
            else config.crawler.max_refusal_check_generated_tokens
        ),
        temperature=1,
        verbose=verbose,
        default_provider=default_provider,
        provider_url_overrides=provider_url_overrides,
        provider_concurrency_limits=provider_concurrency_limits,
        prefer_nitro=prefer_nitro,
    )

    # Remove thinking context from queries if present
    all_queries = remove_thinking_context(all_queries)

    # Step 2: Build mixed query probes and collect topics that need answer checks
    topics_needing_answers = []
    topic_to_queries = {}  # Map topic_idx -> list of queries

    for topic_idx, topic in enumerate(selected_topics):
        # Extract queries for this topic
        start_idx = topic_idx * num_checks
        end_idx = start_idx + num_checks
        queries = all_queries[start_idx:end_idx]
        prompts = all_query_input_strs[start_idx:end_idx]

        fallback_query = f"Tell me about {topic.shortened or topic.raw}"
        queries = _build_refusal_check_queries(
            generated_queries=queries,
            fallback_query=fallback_query,
            num_checks=num_checks,
            threshold=threshold,
        )
        fallback_count = sum(1 for q in queries if q == fallback_query)

        if verbose:
            print(
                f"Topic {topic_idx}: sampled_refusal_check_queries: "
                f"{len(queries)} total, {fallback_count} fallback"
            )
            print(f"queries: {queries}")

        topic.is_refusal = False
        topic_to_queries[topic_idx] = queries
        topics_needing_answers.append(topic_idx)

    # Step 3: Generate answers for all non-refused topics in parallel
    if topics_needing_answers:
        all_answer_prompts = []
        answer_topic_indices = []  # Track which prompts belong to which topic
        # Filtered per-topic queries (post empty-strip) — used in step 4 so that
        # the answer slice counts match the actual batch size, not the original
        # unfiltered count which can drift when empty queries are dropped.
        extracted_topic_queries: Dict[int, List[str]] = {}

        for topic_idx in topics_needing_answers:
            queries = topic_to_queries[topic_idx]
            # Extract user messages from queries
            extracted_queries = [
                re.split(
                    r"<\|assistant\|>|Assistant:|\nassistant\n",
                    query,
                    flags=re.IGNORECASE,
                )[-1].strip(" <>|:")
                for query in queries
            ]
            # Drop any that became empty after stripping role markers / think tags.
            extracted_queries = [q for q in extracted_queries if q.strip()]
            if not extracted_queries:
                extracted_queries = [f"Tell me about {topic.shortened or topic.raw}"]
            extracted_topic_queries[topic_idx] = extracted_queries
            all_answer_prompts.extend(extracted_queries)
            answer_topic_indices.extend([topic_idx] * len(extracted_queries))

        # Generate all answers at once
        #
        # For local reasoning models (Qwen3, DeepSeek-R1, …) the model opens a
        # <think>…</think> block before giving any substantive answer.  With
        # max_refusal_check_generated_tokens as low as 25 that thinking preamble
        # would consume every token, leaving nothing for the classifier to read.
        # We detect this from the tokenizer's chat template and, when applicable,
        # inject a closing-think prefill so generation begins immediately with the
        # answer.  Non-reasoning models (Llama-3, Mistral, Tulu, …) return None
        # from get_thinking_skip_prefill and receive no prefill at all.
        think_skip = (
            get_thinking_skip_prefill(target_tokenizer)
            if target_tokenizer is not None
            else None
        )
        answer_messages = []
        for p in all_answer_prompts:
            if think_skip is not None:
                answer_messages.append(
                    [
                        {"role": "user", "content": p},
                        {"role": "assistant", "content": think_skip},
                    ]
                )
            else:
                answer_messages.append([{"role": "user", "content": p}])

        all_answers, all_answer_strs = batch_generate(
            target_model,
            target_tokenizer,
            answer_messages,
            max_new_tokens=config.crawler.max_refusal_check_generated_tokens,
            temperature=config.model.temperature,
            default_provider=default_provider,
            provider_url_overrides=provider_url_overrides,
            provider_concurrency_limits=provider_concurrency_limits,
            prefer_nitro=prefer_nitro,
        )

        # Step 4: Collect all answers into one flat batch for cascade refusal check.
        # Previously this called check_refusals_cascade once per topic (O(T) serial
        # asyncio.run() calls against the judge model); now it fires a single batched
        # call covering all topics at once, matching the pattern of steps 1 and 3.
        flat_answers = []
        flat_queries = []
        flat_offsets = []  # (topic_idx, flat_start, flat_end)
        offset = 0
        for topic_idx in topics_needing_answers:
            # Use the post-filter extracted query count, not the original
            # topic_to_queries count.  Empty-query drops in step 3 mean
            # all_answers has fewer entries per topic than topic_to_queries,
            # so using the original count causes offset drift and
            # cross-topic answer mis-assignment.
            eq = extracted_topic_queries[topic_idx]
            n = len(eq)
            start = len(flat_answers)
            flat_answers.extend(all_answers[offset : offset + n])
            flat_queries.extend(eq)
            flat_offsets.append((topic_idx, start, start + n))
            offset += n

        flat_refusals = check_refusals_cascade(
            flat_answers,
            config,
            refusal_model,
            refusal_tokenizer,
            translation_model,
            translation_tokenizer,
            queries=flat_queries,
        )

        # Distribute results back to topics
        offset = 0
        for topic_idx, flat_start, flat_end in flat_offsets:
            topic = selected_topics[topic_idx]
            n = flat_end - flat_start
            answers = all_answers[offset : offset + n]
            answer_strs = all_answer_strs[offset : offset + n]
            offset += n

            refused_to_answer_query = flat_refusals[flat_start:flat_end]
            make_answer_majority_refusal = (
                sum(refused_to_answer_query) / len(refused_to_answer_query)
            ) > threshold

            if verbose:
                print(
                    f"Topic {topic_idx}: make_answer_majority_refusal: {make_answer_majority_refusal}"
                )
                print(f"answers: {answers}")

            topic.refusal_check_queries = answer_strs
            topic.refusal_check_responses = answers
            if make_answer_majority_refusal:
                topic.is_refusal = True

            # Extract API moderation reasons if present
            api_reasons = []
            for answer in answers:
                if answer.startswith(API_MODERATION_SENTINEL):
                    api_reasons.append(
                        answer.split(": ", 1)[1] if ": " in answer else "unknown"
                    )
            if api_reasons:
                topic.api_refused_reason = "; ".join(api_reasons)
                meaningful_reasons = [r for r in api_reasons if r.lower() != "unknown"]
                if meaningful_reasons:
                    topic.summary = "; ".join(meaningful_reasons)

    return selected_topics
